### ISSUE TITLE
docker-credential-helpers segfaults (free(): invalid pointer) if list() fails

### ISSUE THREAD

**Issue by nneonneo** [docker/docker-credential-helpers#104]
https://github.com/docker/docker-credential-helpers/blob/19b711cc92fbaa47533646fa8adb457d199c99e1/secretservice/secretservice_linux.go#L96
The wrong free() function is used here - it needs to call `g_error_free(err)` instead of `free`, as it does on e.g. line [72](https://github.com/docker/docker-credential-helpers/blob/19b711cc92fbaa47533646fa8adb457d199c99e1/secretservice/secretservice_linux.go#L72). This has caused several crashes in the wild: see for example https://github.com/moby/moby/issues/34048, https://github.com/docker/for-linux/issues/185, https://github.com/elastic/elasticsearch-docker/issues/163, and I most recently ran into this issue myself on a build machine.

There is an active PR to fix this issue (#29) and another issue (#23) but neither has had any activity in nearly 2 years. The PR is good - please merge it.

**Comment by AdamLeyshon** [comment]
I'm also getting this when trying to build a docker image.
Not sure why it suddenly started since I already build several images today.

```
SIGABRT: abort
PC=0x7f42cc856e97 m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4afd50, 0xc420045cc0, 0xc420045ce8)
        /usr/lib/go-1.8/src/runtime/cgocall.go:131 +0xe2 fp=0xc420045c90 sp=0xc420045c50
github.com/docker/docker-credential-helpers/secretservice._Cfunc_free(0x2359da0)
        github.com/docker/docker-credential-helpers/secretservice/_obj/_cgo_gotypes.go:111 +0x41 fp=0xc420045cc0 sp=0xc420045c90
github.com/docker/docker-credential-helpers/secretservice.Secretservice.List.func5(0x2359da0)
```

**Comment by xNoele** [comment]
I am also currently getting this issue, host os ubuntu, I assume 14-16, I'm not sure on the exact version, as my servers are usually running debian.

```
free(): invalid pointer
SIGABRT: abort
PC=0x7f88d105ee97 m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4afd50, 0xc42004dcc0, 0xc42004dce8)
        /usr/lib/go-1.8/src/runtime/cgocall.go:131 +0xe2 fp=0xc42004dc90 sp=0xc42004dc50
github.com/docker/docker-credential-helpers/secretservice._Cfunc_free(0x1844da0)
        github.com/docker/docker-credential-helpers/secretservice/_obj/_cgo_gotypes.go:111 +0x41 fp=0xc42004dcc0 sp=0xc42004dc90
github.com/docker/docker-credential-helpers/secretservice.Secretservice.List.func5(0x1844da0)
        /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:96 +0x60 fp=0xc42004dcf8 sp=0xc42004dcc0
github.com/docker/docker-credential-helpers/secretservice.Secretservice.List(0x0, 0x756060, 0xc420016390)
        /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:97 +0x217 fp=0xc42004dda0 sp=0xc42004dcf8
github.com/docker/docker-credential-helpers/secretservice.(*Secretservice).List(0x77e548, 0xc42004de88, 0x410022, 0xc4200162f0)
        <autogenerated>:4 +0x46 fp=0xc42004dde0 sp=0xc42004dda0
github.com/docker/docker-credential-helpers/credentials.List(0x756ba0, 0x77e548, 0x7560e0, 0xc42000e018, 0x0, 0x10)
        /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:145 +0x3e fp=0xc42004de68 sp=0xc42004dde0
github.com/docker/docker-credential-helpers/credentials.HandleCommand(0x756ba0, 0x77e548, 0x7ffd3fe5683e, 0x4, 0x7560a0, 0xc42000e010, 0x7560e0, 0xc42000e018, 0x40e398, 0x4d35c0)
        /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:60 +0x16d fp=0xc42004ded8 sp=0xc42004de68
github.com/docker/docker-credential-helpers/credentials.Serve(0x756ba0, 0x77e548)
        /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:41 +0x1cb fp=0xc42004df58 sp=0xc42004ded8
main.main()
        /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/secretservice/cmd/main_linux.go:9 +0x4f fp=0xc42004df88 sp=0xc42004df58
runtime.main()
        /usr/lib/go-1.8/src/runtime/proc.go:185 +0x20a fp=0xc42004dfe0 sp=0xc42004df88
runtime.goexit()
        /usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc42004dfe8 sp=0xc42004dfe0
```

**Comment by wsams** [comment]
Same here on Ubuntu 18.04. I built a vanilla 18.04 on digital ocean and followed this guide to install docker-ce. https://docs.docker.com/install/linux/docker-ce/ubuntu/#upgrade-docker-ce

```
free(): invalid pointer
SIGABRT: abort
PC=0x7eff0a877e97 m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4afd50, 0xc420045cc0, 0xc420045ce8)
        /usr/lib/go-1.8/src/runtime/cgocall.go:131 +0xe2 fp=0xc420045c90 sp=0xc420045c50
github.com/docker/docker-credential-helpers/secretservice._Cfunc_free(0xe9cda0)
        github.com/docker/docker-credential-helpers/secretservice/_obj/_cgo_gotypes.go:111 +0x41 fp=0xc420045cc0 sp=0xc420045c90
github.com/docker/docker-credential-helpers/secretservice.Secretservice.List.func5(0xe9cda0)
        /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:96 +0x60 fp=0xc420045cf8 sp=0xc420045cc0
github.com/docker/docker-credential-helpers/secretservice.Secretservice.List(0x0, 0x756060, 0xc420014380)
        /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/
docker/docker-credential-helpers/secretservice/secretservice_linux.go:97 +0x217 fp=0xc420045da0 sp=0xc420045cf8
github.com/docker/docker-credential-helpers/secretservice.(*Secretservice).List(0x77e548, 0xc420045e88, 0x410022, 0xc4200142e0)
        <autogenerated>:4 +0x46 fp=0xc420045de0 sp=0xc420045da0
github.com/docker/docker-credential-helpers/credentials.List(0x756ba0, 0x77e548, 0x7560e0, 0xc42000e018, 0x0, 0x10)
        /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:145 +0x3e fp=0xc420045e68 sp=0xc420045de0
github.com/docker/docker-credential-helpers/credentials.HandleCommand(0x756ba0, 0x77e548, 0x7fff17744e1f, 0x4, 0x7560a0, 0xc42000e010, 0x7560e0, 0xc42000e018, 0x40e398, 0x4d35c0)
        /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:60 +0x16d fp=0xc420045ed8 sp=0xc420045e68
github.com/docker/docker-credential-helpers/credentials.Serve(0x756ba0, 0x77e548)
        /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:41 +0x1cb fp=0xc420045f58 sp=0xc420045ed8
main.main()
        /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/secretservice/cmd/main_linux.go:9 +0x4f fp=0xc420045f88 sp=0xc420045f58
runtime.main()
        /usr/lib/go-1.8/src/runtime/proc.go:185 +0x20a fp=0xc420045fe0 sp=0xc420045f88
runtime.goexit()
        /usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420045fe8 sp=0xc420045fe0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1

rax    0x0
rbx    0x7fff17742fd0
rcx    0x7eff0a877e97
rdx    0x0
rdi    0x2
rsi    0x7fff17742d60
rbp    0x7fff177430d0
rsp    0x7fff17742d60
r8     0x0
r9     0x7fff17742d60
r10    0x8
r11    0x246
r12    0x7fff17742fd0
r13    0x1000
r14    0x0
r15    0x30
rip    0x7eff0a877e97
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
```

**Comment by basil** [comment]
I hit this on Ubuntu 18.04 LTS with `docker-ce` version `18.06.0~ce~3-0~ubuntu`:

```
free(): invalid pointer
SIGABRT: abort
PC=0x7fcf65ec1e97 m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4afd50, 0xc42004fcc0, 0xc42004fce8)
	/usr/lib/go-1.8/src/runtime/cgocall.go:131 +0xe2 fp=0xc42004fc90 sp=0xc42004fc50
github.com/docker/docker-credential-helpers/secretservice._Cfunc_free(0x820270)
	github.com/docker/docker-credential-helpers/secretservice/_obj/_cgo_gotypes.go:111 +0x41 fp=0xc42004fcc0 sp=0xc42004fc90
github.com/docker/docker-credential-helpers/secretservice.Secretservice.List.func5(0x820270)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:96 +0x60 fp=0xc42004fcf8 sp=0xc42004fcc0
github.com/docker/docker-credential-helpers/secretservice.Secretservice.List(0x0, 0x756060, 0xc420018370)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:97 +0x217 fp=0xc42004fda0 sp=0xc42004fcf8
github.com/docker/docker-credential-helpers/secretservice.(*Secretservice).List(0x77e548, 0xc42004fe88, 0x410022, 0xc4200182c0)
	<autogenerated>:4 +0x46 fp=0xc42004fde0 sp=0xc42004fda0
github.com/docker/docker-credential-helpers/credentials.List(0x756ba0, 0x77e548, 0x7560e0, 0xc42000e018, 0x0, 0x10)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:145 +0x3e fp=0xc42004fe68 sp=0xc42004fde0
github.com/docker/docker-credential-helpers/credentials.HandleCommand(0x756ba0, 0x77e548, 0x7ffc3303078a, 0x4, 0x7560a0, 0xc42000e010, 0x7560e0, 0xc42000e018, 0x40e398, 0x4d35c0)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:60 +0x16d fp=0xc42004fed8 sp=0xc42004fe68
github.com/docker/docker-credential-helpers/credentials.Serve(0x756ba0, 0x77e548)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:41 +0x1cb fp=0xc42004ff58 sp=0xc42004fed8
main.main()
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/secretservice/cmd/main_linux.go:9 +0x4f fp=0xc42004ff88 sp=0xc42004ff58
runtime.main()
	/usr/lib/go-1.8/src/runtime/proc.go:185 +0x20a fp=0xc42004ffe0 sp=0xc42004ff88
runtime.goexit()
	/usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc42004ffe8 sp=0xc42004ffe0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1

rax    0x0
rbx    0x7ffc3302e850
rcx    0x7fcf65ec1e97
rdx    0x0
rdi    0x2
rsi    0x7ffc3302e5e0
rbp    0x7ffc3302e950
rsp    0x7ffc3302e5e0
r8     0x0
r9     0x7ffc3302e5e0
r10    0x8
r11    0x246
r12    0x7ffc3302e850
r13    0x1000
r14    0x0
r15    0x30
rip    0x7fcf65ec1e97
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
```

**Comment by kometchtech** [comment]
I am troubled with similar phenomenon.
The environment is "Ubuntu 18.04.1".
```
free(): invalid pointer
SIGABRT: abort
PC=0x7f8e1a24d8 m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x49fb28, 0x4420057cd8, 0x29)
        /usr/lib/go-1.8/src/runtime/cgocall.go:131 +0x9c fp=0x4420057ca0 sp=0x4420057c60
github.com/docker/docker-credential-helpers/secretservice._Cfunc_free(0x3017270)
        github.com/docker/docker-credential-helpers/secretservice/_obj/_cgo_gotypes.go:111 +0x38 fp=0x4420057cd0 sp=0x4420057ca0
github.com/docker/docker-credential-helpers/secretservice.Secretservice.List.func5(0x3017270)
        /build/golang-github-docker-docker-credential-helpers-iveBZG/golang-github-docker-docker-credential-helpers-0.5.0/obj-aarch64-linux-gnu/src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:96 +0x44 fp=0x4420057d00 sp=0x4420057cd0
github.com/docker/docker-credential-helpers/secretservice.Secretservice.List(0x0, 0x554f80, 0x4420018350)
        /build/golang-github-docker-docker-credential-helpers-iveBZG/golang-github-docker-docker-credential-helpers-0.5.0/obj-aarch64-linux-gnu/src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:97 +0x1c4 fp=0x4420057da0 sp=0x4420057d00
github.com/docker/docker-credential-helpers/secretservice.(*Secretservice).List(0x57b3b8, 0x40ed60, 0x442000c001, 0x40e80c)
        <autogenerated>:4 +0x48 fp=0x4420057de0 sp=0x4420057da0
github.com/docker/docker-credential-helpers/credentials.List(0x555ac0, 0x57b3b8, 0x555000, 0x442000e018, 0x0, 0x0)
        /build/golang-github-docker-docker-credential-helpers-iveBZG/golang-github-docker-docker-credential-helpers-0.5.0/obj-aarch64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:145 +0x28 fp=0x4420057e60 sp=0x4420057de0
github.com/docker/docker-credential-helpers/credentials.HandleCommand(0x555ac0, 0x57b3b8, 0x7fd7ebf750, 0x4, 0x554fc0, 0x442000e010, 0x555000, 0x442000e018, 0x44200182d0, 0x49f99c)
        /build/golang-github-docker-docker-credential-helpers-iveBZG/golang-github-docker-docker-credential-helpers-0.5.0/obj-aarch64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:60 +0x12c fp=0x4420057ed0 sp=0x4420057e60
github.com/docker/docker-credential-helpers/credentials.Serve(0x555ac0, 0x57b3b8)
        /build/golang-github-docker-docker-credential-helpers-iveBZG/golang-github-docker-docker-credential-helpers-0.5.0/obj-aarch64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:41 +0x1a0 fp=0x4420057f50 sp=0x4420057ed0
main.main()
        /build/golang-github-docker-docker-credential-helpers-iveBZG/golang-github-docker-docker-credential-helpers-0.5.0/secretservice/cmd/main_linux.go:9 +0x40 fp=0x4420057f80 sp=0x4420057f50
runtime.main()
        /usr/lib/go-1.8/src/runtime/proc.go:185 +0x1f4 fp=0x4420057fd0 sp=0x4420057f80
runtime.goexit()
        /usr/lib/go-1.8/src/runtime/asm_arm64.s:981 +0x4 fp=0x4420057fd0 sp=0x4420057fd0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/go-1.8/src/runtime/asm_arm64.s:981 +0x4

r0      0x0
r1      0x7fd7ebebc8
r2      0x0
r3      0x8
r4      0x0
r5      0x7fd7ebebc8
r6      0xffffffffffffffff
r7      0xffffffffffffffff
r8      0x87
r9      0xffffffffffffffff
r10     0xffffffffffffffff
r11     0xffffffffffffffff
r12     0xffffffffffffffff
r13     0xffffffffffffffff
r14     0x8
r15     0x0
r16     0x54e168
r17     0x7f8e1e7838
r18     0x7f8e2c3a70
r19     0x7f8e2c2000
r20     0x6
r21     0x7f8e4e2000
r22     0x7fd7ebee00
r23     0x2
r24     0x7f8e2c2000
r25     0x1
r26     0x7f8e299778
r27     0x2
r28     0x7fd7ebee30
r29     0x7fd7ebeba0
lr      0x7f8e1a2464
sp      0x7fd7ebeba0
pc      0x7f8e1a24d8
fault   0x0
```

**Comment by mikma** [comment]
I'm also getting this error on Ubuntu 18.04 server. My workaround is to forward the D-Bus socket from the server to my desktop (also Ubunty 18.04). It seems to work, at least I'm able to build docker containers but I'm not sure when the credential helpers are used.

`ssh -R /run/user/<server uid>/bus:/run/user/<desktop uid>/bus ubuntu@docker.lxd`

**Comment by bevinhex** [comment]
Is there any other workaround for this?

**Comment by cdjc** [comment]
This is biting me as well. ubuntu server 18.04.1. Tried with docker.io from the ubuntu repo as well as docker-ce from the docker repo (edge and stable). Same result. The workaround of @mikma does not apply to my situation. I see the fix is stuck in code review.... :-(

**Comment by twobombs** [comment]
got this too on new 18.04.1 builds
pretty please fix -tnx 📦

**Comment by kierzo** [comment]
Same issue here. Currently running under Ubuntu 18.04 running under an esxi vm, have also moved the default install location via symlink to a mounted drive.

**Comment by ishanjain28** [comment]
Same issue. 

Ubuntu 18.04 

    Linux MoatFund 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

```
free(): invalid pointer
SIGABRT: abort
PC=0x7fec87089e97 m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4afd50, 0xc420051cc0, 0xc420051ce8)
    /usr/lib/go-1.8/src/runtime/cgocall.go:131 +0xe2 fp=0xc420051c90 sp=0xc420051c50
github.com/docker/docker-credential-helpers/secretservice._Cfunc_free(0x15b5270)
    github.com/docker/docker-credential-helpers/secretservice/_obj/_cgo_gotypes.go:111 +0x41 fp=0xc420051cc0 sp=0xc420051c90
github.com/docker/docker-credential-helpers/secretservice.Secretservice.List.func5(0x15b5270)
    /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:96 +0x60 fp=0xc420051cf8 sp=0xc420051cc0
github.com/docker/docker-credential-helpers/secretservice.Secretservice.List(0x0, 0x756060, 0xc420018350)
    /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:97 +0x217 fp=0xc420051da0 sp=0xc420051cf8
github.com/docker/docker-credential-helpers/secretservice.(*Secretservice).List(0x77e548, 0xc420051e88, 0x410022, 0xc4200182b0)
    <autogenerated>:4 +0x46 fp=0xc420051de0 sp=0xc420051da0
github.com/docker/docker-credential-helpers/credentials.List(0x756ba0, 0x77e548, 0x7560e0, 0xc42000e018, 0x0, 0x10)
    /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:145 +0x3e fp=0xc420051e68 sp=0xc420051de0
github.com/docker/docker-credential-helpers/credentials.HandleCommand(0x756ba0, 0x77e548, 0x7ffd28b657b1, 0x4, 0x7560a0, 0xc42000e010, 0x7560e0, 0xc42000e018, 0x40e398, 0x4d35c0)
    /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:60 +0x16d fp=0xc420051ed8 sp=0xc420051e68
github.com/docker/docker-credential-helpers/credentials.Serve(0x756ba0, 0x77e548)
    /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:41 +0x1cb fp=0xc420051f58 sp=0xc420051ed8
main.main()
    /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/secretservice/cmd/main_linux.go:9 +0x4f fp=0xc420051f88 sp=0xc420051f58
runtime.main()
    /usr/lib/go-1.8/src/runtime/proc.go:185 +0x20a fp=0xc420051fe0 sp=0xc420051f88
runtime.goexit()
    /usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420051fe8 sp=0xc420051fe0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1

rax    0x0
rbx    0x7ffd28b63260
rcx    0x7fec87089e97
rdx    0x0
rdi    0x2
rsi    0x7ffd28b62ff0
rbp    0x7ffd28b63360
rsp    0x7ffd28b62ff0
r8     0x0
r9     0x7ffd28b62ff0
r10    0x8
r11    0x246
r12    0x7ffd28b63260
r13    0x1000
r14    0x0
r15    0x30
rip    0x7fec87089e97
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
```

**Comment by nneonneo** [comment]
As far as I can tell, this issue has been fixed in 73e5f5d. If you’re running into the issue, try building it from source and testing again. 

The maintainers should make a new release, so that fixed versions can eventually propagate to downstream repositories.

**Comment by ishanjain28** [comment]
I installed docker with the script available at https://get.docker.com. So, I should have the latest version of docker installed. I'll try building it from source.

**Comment by ishanjain28** [comment]
The latest version of `docker-credential-helpers` doesn't have this bug.

**Comment by slyrus** [comment]
I too am seeing this on 18.04.

**Comment by darkguy2008** [comment]
Same here 18.04.1...

**Comment by mlippert** [comment]
I just ran into this issue. I used the latest Ubuntu 18.04 image for an AWS instance, and then installed Docker CE.
I also installed docker-compose. This is the package that depends on the `golang-docker-credential-helpers` package which seems to be causing the issue.
As I need `docker-compose` I didn't want to uninstall `golang-docker-credential-helpers`.
As @nneonneo said above, there is no release that contains the fix, but it has been merged to the master branch of [docker-credential-helpers](https://github.com/docker/docker-credential-helpers).

You'll have to build it from sources for which you'll need go (`snap install go --classic`) and pkg-config(`apt-get install pkg-config`). Follow the readme to get the sources and then `make secretservice`.

Lastly I put the resulting binary in `/usr/local/bin` which is on the path ahead of /usr/bin.

After all of that the error no longer happens. I hope this helps others until a new release is created and put in the bionic repo.

**Comment by joepvd** [comment]
In the mean while, v0.6.2 has been released of `golang-docker-credential-helpers`, so the building step from :point_up:  may be skipped, and just grab the [latest release](https://github.com/docker/docker-credential-helpers/releases/latest).

**Comment by thaJeztah** [comment]
This should be fixed by https://github.com/docker/docker-credential-helpers/pull/29 - closing
