### ISSUE TITLE
Update wincred

### ISSUE THREAD

**Issue by emersion** [docker/docker-credential-helpers#21]
A panic is triggered otherwise:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x7fc67e]

goroutine 21 [running]:
panic(0x912f80, 0xc0820020a0)
        C:/Go/src/runtime/panic.go:481 +0x3f4
github.com/docker/docker-credential-helpers/vendor/github.com/danieljoos/wincred.nativeToCredential(0x0, 0xc082122000)
        C:/Users/tablet-143/go/src/github.com/docker/docker-credential-helpers/vendor/github.com/danieljoos/wincred/conversion.go:42 +0x4e
github.com/docker/docker-credential-helpers/vendor/github.com/danieljoos/wincred.nativeCredRead(0xc08211a030, 0x27, 0x1, 0x0, 0x0, 0x0)
        C:/Users/tablet-143/go/src/github.com/docker/docker-credential-helpers/vendor/github.com/danieljoos/wincred/native.go:70 +0x1e1
github.com/docker/docker-credential-helpers/vendor/github.com/danieljoos/wincred.GetGenericCredential(0xc08211a030, 0x27, 0xc08211a052, 0x0, 0x0)
        C:/Users/tablet-143/go/src/github.com/docker/docker-credential-helpers/vendor/github.com/danieljoos/wincred/wincred.go:9 +0x4a
github.com/docker/docker-credential-helpers/wincred.Wincred.Get(0xc08211a030, 0x27, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        C:/Users/tablet-143/go/src/github.com/docker/docker-credential-helpers/wincred/wincred_windows.go:34 +0x60
github.com/docker/docker-credential-helpers/wincred.(*Wincred).Get(0xdb3680, 0xc08211a030, 0x27, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        <autogenerated>:3 +0xd2
```

**Comment by danieljoos** [comment]
Can be closed.
