### ISSUE TITLE
User interaction is not allowed

### ISSUE THREAD

**Issue by xanview** [docker/docker-credential-helpers#82]
When I run docker-compose locally, it works just fine, but if I ssh into the machine I get the following:

```
$ docker-compose up                                                                             
Building web
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 68, in main
  File "compose/cli/main.py", line 118, in perform_command
  File "compose/cli/main.py", line 926, in up
  File "compose/project.py", line 401, in up
  File "compose/service.py", line 311, in ensure_image_exists
  File "compose/service.py", line 888, in build
  File "site-packages/docker/api/build.py", line 207, in build
  File "site-packages/docker/api/build.py", line 254, in _set_auth_headers
  File "site-packages/docker/auth.py", line 85, in resolve_authconfig
  File "site-packages/docker/auth.py", line 129, in _resolve_authconfig_credstore
docker.errors.DockerException: Credentials store error: StoreError('Credentials store docker-credential-osxkeychain exited with "User interaction is not allowed.".',)
Failed to execute script docker-compose
```

Any ideas?

**Comment by xanview** [comment]
If I click on the docker icon in the menu bar -> preferences -> and I untick "Securely store docker logins in macOS keychain" this problem goes away.

**Comment by juancarlosfarah** [comment]
I'm experiencing the same issue. Unticking as suggested by @xanview worked for me too, but it would good to know how to fix it without that workaround.

**Comment by aumana** [comment]
I just experienced the same issue

**Comment by antipin** [comment]
I've got the same error when executed ``docker-compose up`` with no PATH env variable available.

**Comment by balsagoth** [comment]
@antipin to me it happens after an OSX crash and somehow the recovered iterm2 sessions are unusable. 
Open a new iterm2 tab solves the problem.

**Comment by wcgcoder** [comment]
Recently I experienced this issue. I went to Keychain Access and locked/unlocked my local keychain. Then I restarted Docker for Mac.

**Comment by mprihoda** [comment]
Running `security unlock-keychain` in the problematic terminal session works for me.

It started to do this to me every time I log in via SSH or use tmux, since one of the last Docker updates (I'm on  17.12.0-ce-mac49 now).

**Comment by n4ss** [comment]
We don't provide a way currently to execute an auto headless unlock of the keychain.

**Comment by ssbarnea** [comment]
Two years later and this is still a serious issue, killing any automation attempts.

I guess the only workaround to this is to go back to non unsing the keychain and getting used to all the runtime warnigns related to unsecured creadentials inside ``~/.docker/config.json``.

**Comment by jamesmehorter** [comment]
Ran into this today, and oddly just had to restart my mac :\

**Comment by raowaqasakram** [comment]
same problem.please anyone

**Comment by collinsmetto** [comment]
Trying the solution offered by @ghost i.e. **clicking on the docker icon in the menu bar -> preferences -> and unticking "Securely store docker logins in macOS keychain"** yielded an initialization error: 

`dockerpycreds.errors.InitializationError: docker-credential-osxkeychain not installed or not available in PATH`
I reticked the  "Securely store docker logins in macOS keychain" and did a docker login afresh. This solved the issue for me.

**Comment by Resch-Said** [comment]
For Windows and Docker Hub:
Docker -> rightclick -> settings -> Shared Drives -> activate your drive(probably C)

**Comment by Daniel123wq** [comment]
Solução para Windows (docker desktop) Faça o seguinte: docker -> configurações -> resoucers -> filesharing -> [disco do projeto] && login com uma conta no docker && restart docker.

**Comment by djismgaming** [comment]
I had to logoff from the Docker Desktop for mac to get rid of this obstacle

**Comment by vatervonacht** [comment]
This is still an issue.  ssh into my macbook pro running docker desktop for mac, 2.5.0.1 (49550).   If I try `docker login` via a remote SSH session I get the following:

```shell
(base) ➜  ~ docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: <my-username>
Password:
Error saving credentials: error storing credentials - err: exit status 1, out: `User interaction is not allowed.`
```
In iTerm2 running directly on macbook pro, everything is fine.  Definitely related to remote SSH sessions on mac.

**Comment by ajslater** [comment]
Shut down docker.
Remove the line:
```json
  "credsStore" : "desktop"
```
from ~/.docker/config.json
Restart docker. Worked for me.
Solution failed at by reading this other issue: https://github.com/docker/for-mac/issues/3774

**Comment by tonistiigi** [comment]
This error means that your keychain is locked and credentials can't be accessed by the current session. Eg. it may stop working when you are log in via ssh like https://github.com/docker/docker-credential-helpers/issues/82#issuecomment-743946708 describes. To unlock the keychain run: `security -v unlock-keychain  ~/Library/Keychains/login.keychain-db`

**Comment by carlitorendon** [comment]
> Shut down docker. Remove the line:
> 
> ```json
>   "credsStore" : "desktop"
> ```
> 
> from ~/.docker/config.json Restart docker. Worked for me. Solution failed at by reading this other issue: [docker/for-mac#3774](https://github.com/docker/for-mac/issues/3774)

@tonistiigi thank you for posting this simple solution. I don't know why anyone would put up with unlocking the keychain (requires typing password) on every terminal session (or vs code session). Also it may be a good idea for Docker to enhance the error message referencing that this is an option.

**Comment by snowdream** [comment]
> Shut down docker. Remove the line:
> 
>   "credsStore" : "desktop"
> from ~/.docker/config.json Restart docker. Worked for me. Solution failed at by reading this other issue: [docker/for-mac#3774](https://github.com/docker/for-mac/issues/3774)

It works for me.
Thank you.
