### ISSUE TITLE
docker runs "pass" always?!

### ISSUE THREAD

**Issue by blueyed** [docker/docker-credential-helpers#96]
I've noticed that just running `docker` will execute `pass`:

```
% strace -f -e file docker
execve("/usr/bin/docker", ["docker"], 0x7ffe510b2898 /* 82 vars */) = 0
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/usr/lib/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/usr/lib/libltdl.so.7", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/usr/lib/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/usr/lib/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
strace: Process 8605 attached
strace: Process 8606 attached
strace: Process 8607 attached
strace: Process 8608 attached
[pid  8604] readlinkat(AT_FDCWD, "/proc/self/exe", "/usr/bin/docker", 128) = 15
[pid  8604] openat(AT_FDCWD, "/proc/sys/net/core/somaxconn", O_RDONLY|O_CLOEXEC) = 3
[pid  8604] stat("/home/user/bin/foo/bin/pass", 0xc4200a0fa8) = -1 ENOENT (No such file or directory)
…
[pid  8604] stat("/usr/bin/pass", {st_mode=S_IFREG|0755, st_size=24974, ...}) = 0
[pid  8604] openat(AT_FDCWD, "/dev/null", O_RDONLY|O_CLOEXEC) = 3
[pid  8604] openat(AT_FDCWD, "/dev/null", O_WRONLY|O_CLOEXEC) = 5
[pid  8604] openat(AT_FDCWD, "/dev/null", O_WRONLY|O_CLOEXEC) = 6
strace: Process 8609 attached
[pid  8609] execve("/usr/bin/pass", ["pass"], 0xc4200b8840 /* 82 vars */) = 0
```

I've tried to configure `credsStore`, but `~/.docker/config.json` gets only read later.

I think this should be avoided?!

Docker version 17.10.0-ce, build f4ffd2511c
Arch Linux

**Comment by deeky666** [comment]
yeah this is weird. was a bit confused as I got en error because of this during an image build:

```
docker-compose build --force-rm php
Building php
Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 124, in perform_command
  File "compose/cli/main.py", line 254, in build
  File "compose/project.py", line 364, in build
  File "compose/service.py", line 967, in build
  File "site-packages/docker/api/build.py", line 250, in build
  File "site-packages/docker/api/build.py", line 297, in _set_auth_headers
  File "site-packages/docker/auth.py", line 97, in resolve_authconfig
  File "site-packages/docker/auth.py", line 142, in _resolve_authconfig_credstore
docker.errors.DockerException: Credentials store error: StoreError('Credentials store docker-credential-pass exited with "pass store is uninitialized".',)
Failed to execute script docker-compose
```
Besides that pass should not be executed on a build, the error appears randomly it seems...

**Comment by AMecea** [comment]
This issue impacts also other projects that uses this package for example [skaffold](https://github.com/GoogleCloudPlatform/skaffold). Always when i start skaffold pass is run and asks for passphrase and makes commits into pass repo. The commit message is ` Add given password for docker-credential-helpers/docker-pass-initialized-check to store.`.

**Comment by onlyjob** [comment]
Docker shoud not run `pass` on every invocation of `docker` command.
